/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarybookborrowing;


import java.sql.*;
import java.awt.Font;
import java.time.LocalDate;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author cknoc
 */
public class Dashboard extends javax.swing.JFrame {
    
    LocalDateTime dateTime = LocalDateTime.now();
    ConnectDatabase db = new ConnectDatabase();
    DateTimeFormatter dateFormat = DateTimeFormatter.ofPattern("MM-dd-yyyy");
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        getDashboard(); // initial load

        // Create a timer that runs every 5000 ms (5 seconds)
        Timer timer = new Timer(5000, e -> {
            getDashboard();
        });

        timer.start(); // start the timer
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlNavigation = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblBorrow = new javax.swing.JLabel();
        lblReturn = new javax.swing.JLabel();
        lblCheckAcc = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        pnlScreen = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnlBorrow = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowList = new javax.swing.JTable();
        pnlBorrowingInfo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBorrowerName = new javax.swing.JTextField();
        txtBorrowBookName = new javax.swing.JTextField();
        txtIssuedBy = new javax.swing.JTextField();
        btnDoneBorrowing = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnDelBook = new javax.swing.JButton();
        pnlReturn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlReturningInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtReceivedBy = new javax.swing.JLabel();
        txtReturneeName = new javax.swing.JTextField();
        txtReturnBookName = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        btnDoneReceive = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        pnlCheckAcc = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtSearchMemberName = new javax.swing.JTextField();
        btnSearchMember = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMemberHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearchMemberID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pnlSearchBook = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearchBookTitle = new javax.swing.JTextField();
        txtSearchYearPublished = new javax.swing.JTextField();
        txtSearchBookAuthor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSearchBook = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 168, 107));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(900, 500));
        setResizable(false);

        pnlBase.setBackground(new java.awt.Color(165, 214, 167));
        pnlBase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        pnlNavigation.setBackground(new java.awt.Color(0, 168, 107));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {50};
        jPanel2Layout.rowHeights = new int[] {60};
        jPanel2Layout.columnWeights = new double[] {30.0, 30.0, 30.0, 30.0, 30.0};
        jPanel2Layout.rowWeights = new double[] {0.0};
        pnlNavigation.setLayout(jPanel2Layout);

        lblHome.setBackground(new java.awt.Color(0, 0, 0));
        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHome.setForeground(new java.awt.Color(0, 0, 0));
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblHome, new java.awt.GridBagConstraints());

        lblBorrow.setBackground(new java.awt.Color(0, 0, 0));
        lblBorrow.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBorrow.setForeground(new java.awt.Color(0, 0, 0));
        lblBorrow.setText("Borrow");
        lblBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBorrowMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblBorrow, new java.awt.GridBagConstraints());

        lblReturn.setBackground(new java.awt.Color(0, 0, 0));
        lblReturn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReturn.setForeground(new java.awt.Color(0, 0, 0));
        lblReturn.setText("Return");
        lblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblReturn, new java.awt.GridBagConstraints());

        lblCheckAcc.setBackground(new java.awt.Color(0, 0, 0));
        lblCheckAcc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCheckAcc.setForeground(new java.awt.Color(0, 0, 0));
        lblCheckAcc.setText("Check Account");
        lblCheckAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCheckAccMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblCheckAcc, new java.awt.GridBagConstraints());

        lblSearch.setBackground(new java.awt.Color(0, 0, 0));
        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblSearch.setText("Search Book");
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblSearch, new java.awt.GridBagConstraints());

        pnlScreen.setBackground(new java.awt.Color(165, 214, 167));
        pnlScreen.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(165, 214, 167));
        pnlHome.setMinimumSize(new java.awt.Dimension(900, 500));

        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Reference Number", "Member Name", "Book Title", "Borrow Date", "Due Date", "Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDashboard.setMinimumSize(new java.awt.Dimension(900, 500));
        tblDashboard.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblDashboard);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1237, Short.MAX_VALUE)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1))
        );

        pnlScreen.add(pnlHome, "card2");

        pnlBorrow.setBackground(new java.awt.Color(165, 214, 167));
        pnlBorrow.setMinimumSize(new java.awt.Dimension(900, 500));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Borrow Book");

        tblBorrowList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member Name", "Book Title", "Issued by", "Borrow Date", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBorrowList.setMinimumSize(new java.awt.Dimension(900, 500));
        jScrollPane2.setViewportView(tblBorrowList);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Member Name:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Book Title:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Issued by:");

        btnDoneBorrowing.setText("Done");
        btnDoneBorrowing.setToolTipText("");
        btnDoneBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneBorrowingActionPerformed(evt);
            }
        });

        btnAddBook.setText("Add Book");
        btnAddBook.setToolTipText("");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnDelBook.setText("Delete Book");
        btnDelBook.setToolTipText("");

        javax.swing.GroupLayout pnlBorrowingInfoLayout = new javax.swing.GroupLayout(pnlBorrowingInfo);
        pnlBorrowingInfo.setLayout(pnlBorrowingInfoLayout);
        pnlBorrowingInfoLayout.setHorizontalGroup(
            pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorrowingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlBorrowingInfoLayout.createSequentialGroup()
                        .addComponent(btnAddBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDelBook))
                    .addGroup(pnlBorrowingInfoLayout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(btnDoneBorrowing))
                    .addComponent(txtBorrowBookName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtBorrowerName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtIssuedBy))
                .addContainerGap())
        );
        pnlBorrowingInfoLayout.setVerticalGroup(
            pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrowingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBorrowerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBorrowBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBook)
                    .addComponent(btnDelBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnDoneBorrowing)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBorrowLayout = new javax.swing.GroupLayout(pnlBorrow);
        pnlBorrow.setLayout(pnlBorrowLayout);
        pnlBorrowLayout.setHorizontalGroup(
            pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlBorrowLayout.createSequentialGroup()
                        .addComponent(pnlBorrowingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlBorrowLayout.setVerticalGroup(
            pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBorrowLayout.createSequentialGroup()
                        .addComponent(pnlBorrowingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlBorrowLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pnlScreen.add(pnlBorrow, "card3");

        pnlReturn.setBackground(new java.awt.Color(165, 214, 167));
        pnlReturn.setMinimumSize(new java.awt.Dimension(900, 500));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Return Book");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Member Name:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Book Title:");

        txtReceivedBy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtReceivedBy.setText("Received by:");

        btnDoneReceive.setText("Done");
        btnDoneReceive.setToolTipText("");
        btnDoneReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneReceiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReturningInfoLayout = new javax.swing.GroupLayout(pnlReturningInfo);
        pnlReturningInfo.setLayout(pnlReturningInfoLayout);
        pnlReturningInfoLayout.setHorizontalGroup(
            pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturningInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReturningInfoLayout.createSequentialGroup()
                        .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReceivedBy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReturnBookName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(txtReturneeName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField6)))
                    .addComponent(btnDoneReceive, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlReturningInfoLayout.setVerticalGroup(
            pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturningInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturneeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturnBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReceivedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoneReceive)
                .addContainerGap())
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Member Name", "Book Title", "Borrow Date", "Due Date", "Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setMinimumSize(new java.awt.Dimension(900, 500));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout pnlReturnLayout = new javax.swing.GroupLayout(pnlReturn);
        pnlReturn.setLayout(pnlReturnLayout);
        pnlReturnLayout.setHorizontalGroup(
            pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReturnLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlReturnLayout.createSequentialGroup()
                        .addComponent(pnlReturningInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 859, Short.MAX_VALUE))))
        );
        pnlReturnLayout.setVerticalGroup(
            pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
                    .addGroup(pnlReturnLayout.createSequentialGroup()
                        .addComponent(pnlReturningInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pnlScreen.add(pnlReturn, "card4");

        pnlCheckAcc.setBackground(new java.awt.Color(165, 214, 167));
        pnlCheckAcc.setMinimumSize(new java.awt.Dimension(900, 500));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Member Name:");

        btnSearchMember.setText("Search");
        btnSearchMember.setToolTipText("");
        btnSearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemberActionPerformed(evt);
            }
        });

        tblMemberHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Trasaction ID", "Member Name", "Book Title", "Borrow Date", "Due Date", "Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMemberHistory.setMinimumSize(new java.awt.Dimension(900, 500));
        jScrollPane4.setViewportView(tblMemberHistory);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member Borrowing History");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Member ID#:");

        javax.swing.GroupLayout pnlCheckAccLayout = new javax.swing.GroupLayout(pnlCheckAcc);
        pnlCheckAcc.setLayout(pnlCheckAccLayout);
        pnlCheckAccLayout.setHorizontalGroup(
            pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckAccLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1225, Short.MAX_VALUE)
                    .addGroup(pnlCheckAccLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchMember)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCheckAccLayout.setVerticalGroup(
            pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckAccLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlScreen.add(pnlCheckAcc, "card5");

        pnlSearchBook.setBackground(new java.awt.Color(165, 214, 167));
        pnlSearchBook.setMinimumSize(new java.awt.Dimension(900, 500));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Search a Book");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Author", "Year Publish", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setMinimumSize(new java.awt.Dimension(900, 500));
        jScrollPane5.setViewportView(jTable5);

        txtSearchBookTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSearchYearPublished.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSearchBookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Enter book title:");

        btnSearchBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchBook.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchBook.setText("Search");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Author:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Year published:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearchBookTitle)
                            .addComponent(txtSearchYearPublished)
                            .addComponent(txtSearchBookAuthor)
                            .addComponent(btnSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGap(272, 272, 272))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSearchBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchYearPublished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchBook)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSearchBookLayout = new javax.swing.GroupLayout(pnlSearchBook);
        pnlSearchBook.setLayout(pnlSearchBookLayout);
        pnlSearchBookLayout.setHorizontalGroup(
            pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBookLayout.createSequentialGroup()
                .addGroup(pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchBookLayout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(875, 875, 875))
                    .addGroup(pnlSearchBookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSearchBookLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlSearchBookLayout.setVerticalGroup(
            pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBookLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                    .addGroup(pnlSearchBookLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlScreen.add(pnlSearchBook, "card6");

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlScreen, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        // removeall, add, repaint, revalidate
        
        pnlScreen.removeAll();
        pnlScreen.add(pnlHome);
        pnlScreen.repaint();
        pnlScreen.revalidate();
        getDashboard();
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblBorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBorrowMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlBorrow);
        pnlScreen.repaint();
        pnlScreen.revalidate();
        
        
    }//GEN-LAST:event_lblBorrowMouseClicked

    private void lblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlReturn);
        pnlScreen.repaint();
        pnlScreen.revalidate();
    }//GEN-LAST:event_lblReturnMouseClicked

    private void lblCheckAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCheckAccMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlCheckAcc);
        pnlScreen.repaint();
        pnlScreen.revalidate();
    }//GEN-LAST:event_lblCheckAccMouseClicked

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlSearchBook);
        pnlScreen.repaint();
        pnlScreen.revalidate();
    }//GEN-LAST:event_lblSearchMouseClicked

    private void btnSearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemberActionPerformed
       
    }//GEN-LAST:event_btnSearchMemberActionPerformed

    private void btnDoneReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneReceiveActionPerformed
        
    }//GEN-LAST:event_btnDoneReceiveActionPerformed

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        borrowAddBook();
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDoneBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneBorrowingActionPerformed
       
        DefaultTableModel doneBorrow = (DefaultTableModel) tblBorrowList.getModel();
        
//        try {
//            Connection conn = db.createConnection();
//
//            // SQL query with all 8 columns
//            String sqlQuery = "INSERT INTO tbl_transaction " +
//                  "(fld_reference_id, fld_member_id, fld_staff_id, fld_book_id, " +
//                  "fld_borrow_date, fld_due_date, fld_status) " +
//                  "VALUES (?, ?, ?, ?, ?, ?, ?)";
//
//            PreparedStatement pstmt = conn.prepareStatement(sqlQuery);
//
//            String referenceId = generateAlphanumericReference(8);
//
//            for (int row = 0; row < doneBorrow.getRowCount(); row++) {
//                pstmt.setString(1, referenceId);
//
//                // Here you’re saving names instead of IDs
//                pstmt.setString(2, doneBorrow.getValueAt(row, 0).toString()); // Member Name
//                pstmt.setString(3, doneBorrow.getValueAt(row, 2).toString()); // Issued By (Staff)
//                pstmt.setString(4, doneBorrow.getValueAt(row, 1).toString()); // Book Title
//
//                // Borrow Date (col 3)
//                String borrowDateStr = doneBorrow.getValueAt(row, 3).toString();
//                LocalDate borrowLocalDate = LocalDate.parse(borrowDateStr, dateFormat);
//                pstmt.setDate(5, java.sql.Date.valueOf(borrowLocalDate));
//
//                // Due Date (col 4)
//                String dueDateStr = doneBorrow.getValueAt(row, 4).toString();
//                LocalDate dueLocalDate = LocalDate.parse(dueDateStr, dateFormat);
//                pstmt.setDate(6, java.sql.Date.valueOf(dueLocalDate));
//
//                // Status
//                pstmt.setString(7, "borrowed");
//
//                pstmt.addBatch();
//            }
//
//
//
//            // Execute all insert statements
//            pstmt.executeBatch();
//
//            JOptionPane.showMessageDialog(this, "All rows inserted successfully!");
//
//            pstmt.close();
//            conn.close();
//
//        } catch (Exception e) {
//            e.printStackTrace();
//            JOptionPane.showMessageDialog(this, "Error: " + e.toString());
//        }

    }//GEN-LAST:event_btnDoneBorrowingActionPerformed

    private static final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    public static String generateAlphanumericReference(int length) {
        Random random = new Random();
        StringBuilder reference = new StringBuilder();
        for (int i = 0; i < length; i++) {
            int index = random.nextInt(CHARACTERS.length());
            reference.append(CHARACTERS.charAt(index));
        }
        return reference.toString();
    }
    
    public void borrowAddBook(){
        
        DefaultTableModel borrowList = (DefaultTableModel) tblBorrowList.getModel();
        
        
        String memberName = txtBorrowerName.getText();
        String issuerName = txtIssuedBy.getText();
        String bookTitle = txtBorrowBookName.getText();
        String dateBorrow = dateTime.format(dateFormat);
        String dueDate = dateTime.plusDays(5).format(dateFormat);
        borrowList.addRow(new Object[]{memberName, bookTitle, issuerName, dateBorrow, dueDate });
        
        txtBorrowBookName.setText("");
    }
    
    
    public void getDashboard() {
        DefaultTableModel dashboard = new DefaultTableModel(
            new String[]{
                "Transaction ID", "Member ID", "Staff ID", "Book ID",
                "Borrow Date", "Due Date", "Return Date", "Status"
            }, 0
        );
        
        
        String sqlQuery = "SELECT fld_reference_id, fld_member_id, fld_staff_id, " +
                     "fld_book_id, fld_borrow_date, fld_due_date, " +
                     "fld_return_date, fld_status " +
                     "FROM tbl_transaction";
        
        try {
            Connection conn = db.createConnection();
            PreparedStatement pstmt = conn.prepareStatement(sqlQuery);
            ResultSet rs = pstmt.executeQuery();
            
            while (rs.next()) {                
                String referenceId = rs.getString("fld_reference_id");
                int memberId = rs.getInt("fld_member_id");
                int staffId = rs.getInt("fld_staff_id");
                int bookId = rs.getInt("fld_book_id");
                Date borrowDate = rs.getDate("fld_borrow_date");
                Date dueDate = rs.getDate("fld_due_date");
                Date returnDate = rs.getDate("fld_return_date");
                String status = rs.getString("fld_status");
                
                dashboard.addRow(new Object[]{
                    referenceId, memberId, staffId, bookId,
                    borrowDate, dueDate, returnDate, status
                });
            }
            
            tblDashboard.setModel(dashboard);
            
            rs.close();
            pstmt.close();
            conn.close();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.
                invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnDelBook;
    private javax.swing.JButton btnDoneBorrowing;
    private javax.swing.JButton btnDoneReceive;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnSearchMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblBorrow;
    private javax.swing.JLabel lblCheckAcc;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBorrow;
    private javax.swing.JPanel pnlBorrowingInfo;
    private javax.swing.JPanel pnlCheckAcc;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JPanel pnlReturningInfo;
    private javax.swing.JPanel pnlScreen;
    private javax.swing.JPanel pnlSearchBook;
    private javax.swing.JTable tblBorrowList;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JTable tblMemberHistory;
    private javax.swing.JTextField txtBorrowBookName;
    private javax.swing.JTextField txtBorrowerName;
    private javax.swing.JTextField txtIssuedBy;
    private javax.swing.JLabel txtReceivedBy;
    private javax.swing.JTextField txtReturnBookName;
    private javax.swing.JTextField txtReturneeName;
    private javax.swing.JTextField txtSearchBookAuthor;
    private javax.swing.JTextField txtSearchBookTitle;
    private javax.swing.JTextField txtSearchMemberID;
    private javax.swing.JTextField txtSearchMemberName;
    private javax.swing.JTextField txtSearchYearPublished;
    // End of variables declaration//GEN-END:variables
}
