/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarybookborrowing;


import java.sql.*;
import java.awt.Font;
import java.time.LocalDate;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JTable;

/**
 *
 * @author cknoc
 */
public class Dashboard extends javax.swing.JFrame {
    
    ConnectDatabase db = new ConnectDatabase();
    Filters callFilters = new Filters();
    LocalDateTime dateTime = LocalDateTime.now();
    Methods callMethods = new Methods();
    
    
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Dashboard.class.getName());

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        callMethods.getBooks(tblAvailBooks);
        callFilters.resizeColumnWidth(tblAvailBooks);
        callFilters.resizeColumnWidth(tblMemberInfo);
        callMethods.refreshDashboard(tblDashboard);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBase = new javax.swing.JPanel();
        pnlNavigation = new javax.swing.JPanel();
        lblHome = new javax.swing.JLabel();
        lblBorrow = new javax.swing.JLabel();
        lblReturn = new javax.swing.JLabel();
        lblCheckAcc = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        pnlScreen = new javax.swing.JPanel();
        pnlHome = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDashboard = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        pnlBorrow = new javax.swing.JPanel();
        lblBorrowList = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBorrowList = new javax.swing.JTable();
        pnlBorrowingInfo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtBorrowerName = new javax.swing.JTextField();
        txtBookTitle = new javax.swing.JTextField();
        txtIssuedBy = new javax.swing.JTextField();
        btnDoneBorrowing = new javax.swing.JButton();
        btnAddBook = new javax.swing.JButton();
        btnDelBook = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblMemberInfo = new javax.swing.JTable();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblStaffInfo = new javax.swing.JTable();
        pnlAvailBooks = new javax.swing.JPanel();
        lblAvailBooks = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblAvailBooks = new javax.swing.JTable();
        pnlReturn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlReturningInfo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtReceivedBy = new javax.swing.JLabel();
        txtReturneeName = new javax.swing.JTextField();
        txtReturnBookName = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        btnDoneReceive = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        pnlCheckAcc = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtSearchMemberName = new javax.swing.JTextField();
        btnSearchMember = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMemberHistory = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtSearchMemberID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        pnlSearchBook = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        txtSearchBookTitle = new javax.swing.JTextField();
        txtSearchYearPublished = new javax.swing.JTextField();
        txtSearchBookAuthor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btnSearchBook = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 168, 107));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(1500, 900));
        setMinimumSize(new java.awt.Dimension(1300, 600));
        setPreferredSize(new java.awt.Dimension(1300, 600));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        pnlBase.setBackground(new java.awt.Color(165, 214, 167));
        pnlBase.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlBase.setMaximumSize(new java.awt.Dimension(1500, 900));
        pnlBase.setPreferredSize(new java.awt.Dimension(1300, 700));

        pnlNavigation.setBackground(new java.awt.Color(0, 168, 107));
        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {50};
        jPanel2Layout.rowHeights = new int[] {60};
        jPanel2Layout.columnWeights = new double[] {30.0, 30.0, 30.0, 30.0, 30.0};
        jPanel2Layout.rowWeights = new double[] {0.0};
        pnlNavigation.setLayout(jPanel2Layout);

        lblHome.setBackground(new java.awt.Color(0, 0, 0));
        lblHome.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblHome.setForeground(new java.awt.Color(0, 0, 0));
        lblHome.setText("Home");
        lblHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHomeMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblHome, new java.awt.GridBagConstraints());

        lblBorrow.setBackground(new java.awt.Color(0, 0, 0));
        lblBorrow.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblBorrow.setForeground(new java.awt.Color(0, 0, 0));
        lblBorrow.setText("Borrow");
        lblBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblBorrowMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblBorrow, new java.awt.GridBagConstraints());

        lblReturn.setBackground(new java.awt.Color(0, 0, 0));
        lblReturn.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblReturn.setForeground(new java.awt.Color(0, 0, 0));
        lblReturn.setText("Return");
        lblReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReturnMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblReturn, new java.awt.GridBagConstraints());

        lblCheckAcc.setBackground(new java.awt.Color(0, 0, 0));
        lblCheckAcc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblCheckAcc.setForeground(new java.awt.Color(0, 0, 0));
        lblCheckAcc.setText("Check Account");
        lblCheckAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCheckAccMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblCheckAcc, new java.awt.GridBagConstraints());

        lblSearch.setBackground(new java.awt.Color(0, 0, 0));
        lblSearch.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblSearch.setForeground(new java.awt.Color(0, 0, 0));
        lblSearch.setText("Search Book");
        lblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSearchMouseClicked(evt);
            }
        });
        pnlNavigation.add(lblSearch, new java.awt.GridBagConstraints());

        pnlScreen.setBackground(new java.awt.Color(165, 214, 167));
        pnlScreen.setMaximumSize(new java.awt.Dimension(1300, 900));
        pnlScreen.setLayout(new java.awt.CardLayout());

        pnlHome.setBackground(new java.awt.Color(165, 214, 167));
        pnlHome.setMaximumSize(new java.awt.Dimension(1300, 900));
        pnlHome.setMinimumSize(new java.awt.Dimension(900, 500));

        jScrollPane1.setMinimumSize(new java.awt.Dimension(1300, 400));

        tblDashboard.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Transaction ID", "Member Name", "Issued By", "Book Title", "Borrow Date", "Due Date", "Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDashboard.setMaximumSize(new java.awt.Dimension(1300, 5000));
        tblDashboard.setMinimumSize(new java.awt.Dimension(900, 500));
        tblDashboard.setPreferredSize(new java.awt.Dimension(1300, 5000));
        tblDashboard.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tblDashboard);

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Dashboard");

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 544, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pnlScreen.add(pnlHome, "card2");

        pnlBorrow.setBackground(new java.awt.Color(165, 214, 167));
        pnlBorrow.setMaximumSize(new java.awt.Dimension(1300, 900));
        pnlBorrow.setMinimumSize(new java.awt.Dimension(1300, 500));

        lblBorrowList.setBackground(new java.awt.Color(0, 0, 0));
        lblBorrowList.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblBorrowList.setForeground(new java.awt.Color(0, 0, 0));
        lblBorrowList.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBorrowList.setText("Borrowing List");

        tblBorrowList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Book Title", "Member Name", "Issued by", "Borrow Date", "Due Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBorrowList.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tblBorrowList.setMinimumSize(new java.awt.Dimension(900, 500));
        tblBorrowList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tblBorrowList);
        if (tblBorrowList.getColumnModel().getColumnCount() > 0) {
            tblBorrowList.getColumnModel().getColumn(0).setResizable(false);
            tblBorrowList.getColumnModel().getColumn(1).setResizable(false);
            tblBorrowList.getColumnModel().getColumn(2).setResizable(false);
            tblBorrowList.getColumnModel().getColumn(3).setResizable(false);
            tblBorrowList.getColumnModel().getColumn(4).setResizable(false);
            tblBorrowList.getColumnModel().getColumn(5).setResizable(false);
        }

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Member Name:");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setText("Book Title:");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setText("Issued by:");

        txtBorrowerName.setMaximumSize(new java.awt.Dimension(64, 22));
        txtBorrowerName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBorrowerNameKeyReleased(evt);
            }
        });

        txtBookTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBookTitleKeyReleased(evt);
            }
        });

        txtIssuedBy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtIssuedByKeyReleased(evt);
            }
        });

        btnDoneBorrowing.setText("Done");
        btnDoneBorrowing.setToolTipText("");
        btnDoneBorrowing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneBorrowingActionPerformed(evt);
            }
        });

        btnAddBook.setText("Add Book");
        btnAddBook.setToolTipText("");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });

        btnDelBook.setText("Delete Book");
        btnDelBook.setToolTipText("");
        btnDelBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBorrowingInfoLayout = new javax.swing.GroupLayout(pnlBorrowingInfo);
        pnlBorrowingInfo.setLayout(pnlBorrowingInfoLayout);
        pnlBorrowingInfoLayout.setHorizontalGroup(
            pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrowingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlBorrowingInfoLayout.createSequentialGroup()
                        .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(225, 225, 225))
                    .addGroup(pnlBorrowingInfoLayout.createSequentialGroup()
                        .addComponent(btnAddBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDelBook)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDoneBorrowing)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorrowingInfoLayout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(274, 274, 274))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorrowingInfoLayout.createSequentialGroup()
                        .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtIssuedBy, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBookTitle, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBorrowerName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        pnlBorrowingInfoLayout.setVerticalGroup(
            pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrowingInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBorrowerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtIssuedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlBorrowingInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBook)
                    .addComponent(btnDelBook)
                    .addComponent(btnDoneBorrowing))
                .addGap(24, 24, 24))
        );

        jScrollPane7.setMaximumSize(new java.awt.Dimension(500, 500));

        tblMemberInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Member ID", "Member Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMemberInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblMemberInfoMouseReleased(evt);
            }
        });
        jScrollPane7.setViewportView(tblMemberInfo);
        if (tblMemberInfo.getColumnModel().getColumnCount() > 0) {
            tblMemberInfo.getColumnModel().getColumn(0).setResizable(false);
            tblMemberInfo.getColumnModel().getColumn(1).setResizable(false);
        }

        jScrollPane8.setMaximumSize(new java.awt.Dimension(500, 500));

        tblStaffInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Staff ID", "Staff Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStaffInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblStaffInfoMouseReleased(evt);
            }
        });
        jScrollPane8.setViewportView(tblStaffInfo);

        pnlAvailBooks.setBackground(new java.awt.Color(165, 214, 167));

        lblAvailBooks.setBackground(new java.awt.Color(0, 0, 0));
        lblAvailBooks.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAvailBooks.setForeground(new java.awt.Color(0, 0, 0));
        lblAvailBooks.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAvailBooks.setText("Available Books");

        tblAvailBooks.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Book Title", "Author", "Publisher", "Year Published"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAvailBooks.setMinimumSize(new java.awt.Dimension(900, 500));
        tblAvailBooks.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblAvailBooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tblAvailBooksMouseReleased(evt);
            }
        });
        jScrollPane6.setViewportView(tblAvailBooks);

        javax.swing.GroupLayout pnlAvailBooksLayout = new javax.swing.GroupLayout(pnlAvailBooks);
        pnlAvailBooks.setLayout(pnlAvailBooksLayout);
        pnlAvailBooksLayout.setHorizontalGroup(
            pnlAvailBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvailBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAvailBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAvailBooks, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAvailBooksLayout.setVerticalGroup(
            pnlAvailBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAvailBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAvailBooks, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlBorrowLayout = new javax.swing.GroupLayout(pnlBorrow);
        pnlBorrow.setLayout(pnlBorrowLayout);
        pnlBorrowLayout.setHorizontalGroup(
            pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(pnlBorrowLayout.createSequentialGroup()
                .addGroup(pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                    .addComponent(pnlBorrowingInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBorrowList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorrowLayout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addGap(4, 4, 4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorrowLayout.createSequentialGroup()
                        .addComponent(pnlAvailBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        pnlBorrowLayout.setVerticalGroup(
            pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBorrowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBorrowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBorrowLayout.createSequentialGroup()
                        .addComponent(pnlBorrowingInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(76, Short.MAX_VALUE))
                    .addGroup(pnlBorrowLayout.createSequentialGroup()
                        .addComponent(lblBorrowList)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlAvailBooks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pnlScreen.add(pnlBorrow, "card3");

        pnlReturn.setBackground(new java.awt.Color(165, 214, 167));
        pnlReturn.setMaximumSize(new java.awt.Dimension(1300, 900));
        pnlReturn.setMinimumSize(new java.awt.Dimension(900, 500));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Return Book");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Member Name:");

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Book Title:");

        txtReceivedBy.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtReceivedBy.setText("Received by:");

        btnDoneReceive.setText("Done");
        btnDoneReceive.setToolTipText("");
        btnDoneReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoneReceiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlReturningInfoLayout = new javax.swing.GroupLayout(pnlReturningInfo);
        pnlReturningInfo.setLayout(pnlReturningInfoLayout);
        pnlReturningInfoLayout.setHorizontalGroup(
            pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturningInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlReturningInfoLayout.createSequentialGroup()
                        .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtReceivedBy, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtReturnBookName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtReturneeName, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField6)))
                    .addComponent(btnDoneReceive, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        pnlReturningInfoLayout.setVerticalGroup(
            pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturningInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturneeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReturnBookName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlReturningInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReceivedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDoneReceive)
                .addContainerGap())
        );

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Member Name", "Book Title", "Borrow Date", "Due Date", "Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable3.setMinimumSize(new java.awt.Dimension(900, 500));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout pnlReturnLayout = new javax.swing.GroupLayout(pnlReturn);
        pnlReturn.setLayout(pnlReturnLayout);
        pnlReturnLayout.setHorizontalGroup(
            pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReturnLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlReturnLayout.createSequentialGroup()
                        .addComponent(pnlReturningInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3))))
        );
        pnlReturnLayout.setVerticalGroup(
            pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReturnLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(12, 12, 12)
                .addGroup(pnlReturnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(pnlReturnLayout.createSequentialGroup()
                        .addComponent(pnlReturningInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        pnlScreen.add(pnlReturn, "card4");

        pnlCheckAcc.setBackground(new java.awt.Color(165, 214, 167));
        pnlCheckAcc.setMaximumSize(new java.awt.Dimension(1300, 900));
        pnlCheckAcc.setMinimumSize(new java.awt.Dimension(900, 500));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Member Name:");

        btnSearchMember.setText("Search");
        btnSearchMember.setToolTipText("");
        btnSearchMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchMemberActionPerformed(evt);
            }
        });

        tblMemberHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Trasaction ID", "Member Name", "Book Title", "Borrow Date", "Due Date", "Return Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMemberHistory.setMinimumSize(new java.awt.Dimension(900, 500));
        jScrollPane4.setViewportView(tblMemberHistory);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Member Borrowing History");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Member ID#:");

        javax.swing.GroupLayout pnlCheckAccLayout = new javax.swing.GroupLayout(pnlCheckAcc);
        pnlCheckAcc.setLayout(pnlCheckAccLayout);
        pnlCheckAccLayout.setHorizontalGroup(
            pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckAccLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4)
                    .addGroup(pnlCheckAccLayout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearchMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSearchMember)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlCheckAccLayout.setVerticalGroup(
            pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCheckAccLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCheckAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchMemberName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchMemberID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchMember))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlScreen.add(pnlCheckAcc, "card5");

        pnlSearchBook.setBackground(new java.awt.Color(165, 214, 167));
        pnlSearchBook.setMaximumSize(new java.awt.Dimension(1300, 900));
        pnlSearchBook.setMinimumSize(new java.awt.Dimension(900, 500));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Search a Book");

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Book ID", "Author", "Year Publish", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable5.setMinimumSize(new java.awt.Dimension(900, 500));
        jScrollPane5.setViewportView(jTable5);

        txtSearchBookTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSearchYearPublished.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        txtSearchBookAuthor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Enter book title:");

        btnSearchBook.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSearchBook.setForeground(new java.awt.Color(0, 0, 0));
        btnSearchBook.setText("Search");

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Author:");

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Year published:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtSearchBookTitle)
                            .addComponent(txtSearchYearPublished)
                            .addComponent(txtSearchBookAuthor)
                            .addComponent(btnSearchBook, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(272, 272, 272))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSearchBookTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtSearchBookAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchYearPublished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchBook)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlSearchBookLayout = new javax.swing.GroupLayout(pnlSearchBook);
        pnlSearchBook.setLayout(pnlSearchBookLayout);
        pnlSearchBookLayout.setHorizontalGroup(
            pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBookLayout.createSequentialGroup()
                .addGroup(pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSearchBookLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(875, 875, 875))
                    .addGroup(pnlSearchBookLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlSearchBookLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 869, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        pnlSearchBookLayout.setVerticalGroup(
            pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSearchBookLayout.createSequentialGroup()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlSearchBookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(pnlSearchBookLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pnlScreen.add(pnlSearchBook, "card6");

        javax.swing.GroupLayout pnlBaseLayout = new javax.swing.GroupLayout(pnlBase);
        pnlBase.setLayout(pnlBaseLayout);
        pnlBaseLayout.setHorizontalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlNavigation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlScreen, javax.swing.GroupLayout.DEFAULT_SIZE, 1355, Short.MAX_VALUE)
        );
        pnlBaseLayout.setVerticalGroup(
            pnlBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBaseLayout.createSequentialGroup()
                .addComponent(pnlNavigation, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlScreen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 1361, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlBase, javax.swing.GroupLayout.DEFAULT_SIZE, 758, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHomeMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlHome);
        pnlScreen.repaint();
        pnlScreen.revalidate();
        callMethods.refreshDashboard(tblDashboard);
    }//GEN-LAST:event_lblHomeMouseClicked

    private void lblBorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBorrowMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlBorrow);
        pnlScreen.repaint();
        pnlScreen.revalidate();
    }//GEN-LAST:event_lblBorrowMouseClicked

    private void lblReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReturnMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlReturn);
        pnlScreen.repaint();
        pnlScreen.revalidate();
    }//GEN-LAST:event_lblReturnMouseClicked

    private void lblCheckAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCheckAccMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlCheckAcc);
        pnlScreen.repaint();
        pnlScreen.revalidate();
    }//GEN-LAST:event_lblCheckAccMouseClicked

    private void lblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSearchMouseClicked
        pnlScreen.removeAll();
        pnlScreen.add(pnlSearchBook);
        pnlScreen.repaint();
        pnlScreen.revalidate();
    }//GEN-LAST:event_lblSearchMouseClicked

    private void btnSearchMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchMemberActionPerformed
       
    }//GEN-LAST:event_btnSearchMemberActionPerformed

    private void btnDoneReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneReceiveActionPerformed
        
    }//GEN-LAST:event_btnDoneReceiveActionPerformed

    private void tblAvailBooksMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAvailBooksMouseReleased
        callMethods.getBookID(tblAvailBooks, txtBookTitle);
    }//GEN-LAST:event_tblAvailBooksMouseReleased

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        if (!txtBookTitle.getText().isEmpty() ) {
            String borrowerName = txtBookTitle.getText();
            String issuerName = txtIssuedBy.getText();
            if (!borrowerName.isEmpty() && !issuerName.isEmpty()) {
                borrowAddBook();
            }
            callFilters.resizeColumnWidth(tblBorrowList);
        }
    }//GEN-LAST:event_btnAddBookActionPerformed

    private void btnDoneBorrowingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoneBorrowingActionPerformed

        String messageResult = "";
        int memberID = callMethods.getFirstCell(tblMemberInfo);
        int staffID = callMethods.getFirstCell(tblStaffInfo);

        DefaultTableModel doneBorrow = (DefaultTableModel) tblBorrowList.getModel();

        try {
            Connection conn = db.createConnection();
            conn.setAutoCommit(false); 

            String sqlInsert = "INSERT INTO tbl_transaction " +
                    "(fld_reference_id, fld_member_id, fld_staff_id, fld_book_id, " +
                    "fld_borrow_date, fld_due_date, fld_status) " +
                    "VALUES (?, ?, ?, ?, ?, ?, ?)";

            String sqlUpdateQty = "UPDATE tbl_book SET fld_quantity = fld_quantity - 1 WHERE fld_book_id = ?";

            PreparedStatement pstmtInsert = conn.prepareStatement(sqlInsert);
            PreparedStatement pstmtUpdate = conn.prepareStatement(sqlUpdateQty);

            String referenceId = callMethods.generateReference(5);

            
            boolean allAvailable = true;
            String unavailableBooks = "";
            for (int row = 0; row < doneBorrow.getRowCount(); row++) {
                int bookId = Integer.parseInt(doneBorrow.getValueAt(row, 0).toString());
                if (!callFilters.isBookAvailable(bookId)) {
                    allAvailable = false;
                    unavailableBooks += "\nBook with ID #" + bookId + " is not available!";
                }
            }

            if (!allAvailable) {
                conn.rollback(); 
                JOptionPane.showMessageDialog(this, "Transaction cancelled!" + unavailableBooks);
                pstmtInsert.close();
                pstmtUpdate.close();
                conn.close();
                return;
            }
            
            for (int row = 0; row < doneBorrow.getRowCount(); row++) {
                int bookId = Integer.parseInt(doneBorrow.getValueAt(row, 0).toString());

                pstmtInsert.setString(1, referenceId);
                pstmtInsert.setInt(2, memberID);
                pstmtInsert.setInt(3, staffID);
                pstmtInsert.setInt(4, bookId);

                String borrowDateStr = doneBorrow.getValueAt(row, 3).toString();
                LocalDateTime borrowLocalDate = callFilters.convertStringToLocalDate(borrowDateStr);
                pstmtInsert.setTimestamp(5, java.sql.Timestamp.valueOf(borrowLocalDate));

                String dueDateStr = doneBorrow.getValueAt(row, 4).toString();
                LocalDateTime dueLocalDate = callFilters.convertStringToLocalDate(dueDateStr);
                pstmtInsert.setTimestamp(6, java.sql.Timestamp.valueOf(dueLocalDate));

                pstmtInsert.setString(7, "Borrowed");
                pstmtInsert.executeUpdate();

                pstmtUpdate.setInt(1, bookId);
                pstmtUpdate.executeUpdate();
            }

            conn.commit();
            messageResult = "Borrowing books success";
            System.out.println("done");
            JOptionPane.showMessageDialog(this, messageResult);

            pstmtInsert.close();
            pstmtUpdate.close();
            conn.close();

        } catch (Exception e) {
            e.printStackTrace();
            try {
                Connection conn = db.createConnection();
                if (conn != null) conn.rollback();
            } catch (SQLException ex) {
                ex.printStackTrace();
            }
            JOptionPane.showMessageDialog(this, "Error: " + e.toString());
        }


    }//GEN-LAST:event_btnDoneBorrowingActionPerformed

    private void txtBorrowerNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBorrowerNameKeyReleased
        String txtin = txtBorrowerName.getText();
        callMethods.searchMemberByLastName(tblMemberInfo, txtin);
    }//GEN-LAST:event_txtBorrowerNameKeyReleased

    private void tblMemberInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMemberInfoMouseReleased
        callMethods.getID(tblMemberInfo, txtBorrowerName);
    }//GEN-LAST:event_tblMemberInfoMouseReleased

    private void btnDelBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelBookActionPerformed
        int selectedRow = tblBorrowList.getSelectedRow(); 

        if (selectedRow != -1) { 
            DefaultTableModel dtm = (DefaultTableModel) tblBorrowList.getModel();
            dtm.removeRow(selectedRow);
        } else {
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
        }
    }//GEN-LAST:event_btnDelBookActionPerformed

    
    private void txtIssuedByKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIssuedByKeyReleased
        String txtin = txtIssuedBy.getText();
        callMethods.searchStaffByLastName(tblStaffInfo, txtin);
    }//GEN-LAST:event_txtIssuedByKeyReleased

    private void tblStaffInfoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStaffInfoMouseReleased
        callMethods.getID(tblStaffInfo, txtIssuedBy);
    }//GEN-LAST:event_tblStaffInfoMouseReleased

    private void txtBookTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookTitleKeyReleased
        String txtin = txtBookTitle.getText();
        callMethods.searchBookTitle(tblAvailBooks, txtin);
    }//GEN-LAST:event_txtBookTitleKeyReleased

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        setExtendedState(this.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    
    public void borrowAddBook(){
        
        DefaultTableModel borrowList = (DefaultTableModel) tblBorrowList.getModel();
        int selectedRow = tblAvailBooks.getSelectedRow();
        Object selectedBook = tblAvailBooks.getValueAt(selectedRow, 0);
        
        String memberName = txtBorrowerName.getText();
        String issuerName = txtIssuedBy.getText();
        String bookTitle = txtBookTitle.getText();
        String dateBorrow = callFilters.convertLocalDateTimeToPattern(dateTime);
        String dueDate = callFilters.convertLocalDateTimeToPattern(dateTime.plusDays(5));
        borrowList.addRow(new Object[]{selectedBook , bookTitle, memberName, issuerName, dateBorrow, dueDate });
        txtBookTitle.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.
                invokeLater(() -> new Dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnDelBook;
    private javax.swing.JButton btnDoneBorrowing;
    private javax.swing.JButton btnDoneReceive;
    private javax.swing.JButton btnSearchBook;
    private javax.swing.JButton btnSearchMember;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JLabel lblAvailBooks;
    private javax.swing.JLabel lblBorrow;
    private javax.swing.JLabel lblBorrowList;
    private javax.swing.JLabel lblCheckAcc;
    private javax.swing.JLabel lblHome;
    private javax.swing.JLabel lblReturn;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JPanel pnlAvailBooks;
    private javax.swing.JPanel pnlBase;
    private javax.swing.JPanel pnlBorrow;
    private javax.swing.JPanel pnlBorrowingInfo;
    private javax.swing.JPanel pnlCheckAcc;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlReturn;
    private javax.swing.JPanel pnlReturningInfo;
    private javax.swing.JPanel pnlScreen;
    private javax.swing.JPanel pnlSearchBook;
    private javax.swing.JTable tblAvailBooks;
    private javax.swing.JTable tblBorrowList;
    private javax.swing.JTable tblDashboard;
    private javax.swing.JTable tblMemberHistory;
    private javax.swing.JTable tblMemberInfo;
    private javax.swing.JTable tblStaffInfo;
    private javax.swing.JTextField txtBookTitle;
    private javax.swing.JTextField txtBorrowerName;
    private javax.swing.JTextField txtIssuedBy;
    private javax.swing.JLabel txtReceivedBy;
    private javax.swing.JTextField txtReturnBookName;
    private javax.swing.JTextField txtReturneeName;
    private javax.swing.JTextField txtSearchBookAuthor;
    private javax.swing.JTextField txtSearchBookTitle;
    private javax.swing.JTextField txtSearchMemberID;
    private javax.swing.JTextField txtSearchMemberName;
    private javax.swing.JTextField txtSearchYearPublished;
    // End of variables declaration//GEN-END:variables
}
