/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package librarybookborrowing;

import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author cknoc
 */
public class Register extends javax.swing.JFrame {
    
    ConnectDatabase db = new ConnectDatabase();
    
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(Register.class.getName());

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlRegister = new javax.swing.JPanel();
        pnlChooseReg = new javax.swing.JPanel();
        lblRegMember = new javax.swing.JLabel();
        lblRegStaff = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlRegMember = new javax.swing.JPanel();
        pnlMemberForm = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtFirstNameMember = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtMidNameMember = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLastNameMember = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPhoneNumberMember = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtEmailMember = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        btnRegisterMember = new javax.swing.JButton();
        pnlRegStaff = new javax.swing.JPanel();
        pnlRegStaffForm = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtFirstNameStaff = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtMidNameStaff = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtLastNameStaff = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUsernameStaff = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtEmailStaff = new javax.swing.JTextField();
        cmbRoles = new javax.swing.JComboBox<>();
        txtPasswordStaff = new javax.swing.JPasswordField();
        txtReEntPasswordStaff = new javax.swing.JPasswordField();
        jLabel18 = new javax.swing.JLabel();
        btnRegisterStaff = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 1000));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(162, 126, 142));

        pnlRegister.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegister.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        pnlRegister.setLayout(new java.awt.CardLayout());

        pnlChooseReg.setBackground(new java.awt.Color(255, 255, 255));

        lblRegMember.setBackground(new java.awt.Color(99, 29, 118));
        lblRegMember.setFont(new java.awt.Font("Century Gothic", 0, 21)); // NOI18N
        lblRegMember.setForeground(new java.awt.Color(255, 255, 255));
        lblRegMember.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegMember.setText("Register as Member");
        lblRegMember.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        lblRegMember.setOpaque(true);
        lblRegMember.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegMemberMouseClicked(evt);
            }
        });

        lblRegStaff.setBackground(new java.awt.Color(99, 29, 118));
        lblRegStaff.setFont(new java.awt.Font("Century Gothic", 0, 21)); // NOI18N
        lblRegStaff.setForeground(new java.awt.Color(255, 255, 255));
        lblRegStaff.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRegStaff.setText("Register as Staff");
        lblRegStaff.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        lblRegStaff.setOpaque(true);
        lblRegStaff.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblRegStaffMouseClicked(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Nirmala UI", 1, 30)); // NOI18N
        jLabel17.setText("Registration");

        javax.swing.GroupLayout pnlChooseRegLayout = new javax.swing.GroupLayout(pnlChooseReg);
        pnlChooseReg.setLayout(pnlChooseRegLayout);
        pnlChooseRegLayout.setHorizontalGroup(
            pnlChooseRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChooseRegLayout.createSequentialGroup()
                .addGroup(pnlChooseRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlChooseRegLayout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(pnlChooseRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblRegStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegMember, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlChooseRegLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel17)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        pnlChooseRegLayout.setVerticalGroup(
            pnlChooseRegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlChooseRegLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addComponent(lblRegMember, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblRegStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pnlRegister.add(pnlChooseReg, "card4");

        pnlRegMember.setBackground(new java.awt.Color(255, 255, 255));

        pnlMemberForm.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("First Name:");

        txtFirstNameMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("MIddle Name:");

        txtMidNameMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Last Name:");

        txtLastNameMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Phone Number:");

        txtPhoneNumberMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Email:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        txtEmailMember.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel19.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel19.setText("Member Registration");

        btnRegisterMember.setBackground(new java.awt.Color(99, 29, 118));
        btnRegisterMember.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnRegisterMember.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterMember.setText("Register");
        btnRegisterMember.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.darkGray, java.awt.Color.darkGray));
        btnRegisterMember.setContentAreaFilled(false);
        btnRegisterMember.setOpaque(true);
        btnRegisterMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterMemberActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMemberFormLayout = new javax.swing.GroupLayout(pnlMemberForm);
        pnlMemberForm.setLayout(pnlMemberFormLayout);
        pnlMemberFormLayout.setHorizontalGroup(
            pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberFormLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMemberFormLayout.createSequentialGroup()
                        .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMemberFormLayout.createSequentialGroup()
                                .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMemberFormLayout.createSequentialGroup()
                                        .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnlMemberFormLayout.createSequentialGroup()
                                                .addGap(103, 103, 103)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(pnlMemberFormLayout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addGap(0, 0, Short.MAX_VALUE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberFormLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberFormLayout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(16, 16, 16))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberFormLayout.createSequentialGroup()
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))))
                                .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtFirstNameMember, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtPhoneNumberMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtLastNameMember, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMidNameMember, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlMemberFormLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmailMember, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberFormLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel19)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMemberFormLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegisterMember, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        pnlMemberFormLayout.setVerticalGroup(
            pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMemberFormLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel19)
                .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMemberFormLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlMemberFormLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFirstNameMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMidNameMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(10, 10, 10)
                        .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtLastNameMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(pnlMemberFormLayout.createSequentialGroup()
                                .addComponent(txtPhoneNumberMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlMemberFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEmailMember, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(btnRegisterMember)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout pnlRegMemberLayout = new javax.swing.GroupLayout(pnlRegMember);
        pnlRegMember.setLayout(pnlRegMemberLayout);
        pnlRegMemberLayout.setHorizontalGroup(
            pnlRegMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegMemberLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(pnlMemberForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );
        pnlRegMemberLayout.setVerticalGroup(
            pnlRegMemberLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegMemberLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(pnlMemberForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pnlRegister.add(pnlRegMember, "card2");

        pnlRegStaff.setBackground(new java.awt.Color(255, 255, 255));

        pnlRegStaffForm.setBackground(new java.awt.Color(255, 255, 255));
        pnlRegStaffForm.setMaximumSize(new java.awt.Dimension(500, 500));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("First Name:");

        txtFirstNameStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("MIddle Name:");

        txtMidNameStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Last Name:");

        txtLastNameStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Username:");

        txtUsernameStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel11.setText("Role:");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Password:");

        jLabel15.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Re-enter Password:");

        jLabel14.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Email:");

        txtEmailStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cmbRoles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Librarian", "Assistant Librarian", "Admin" }));
        cmbRoles.setSelectedIndex(-1);

        txtPasswordStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        txtReEntPasswordStaff.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtReEntPasswordStaff.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtReEntPasswordStaffFocusLost(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Nirmala UI", 1, 36)); // NOI18N
        jLabel18.setText("Staff Registration");

        btnRegisterStaff.setBackground(new java.awt.Color(99, 29, 118));
        btnRegisterStaff.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        btnRegisterStaff.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterStaff.setText("Register");
        btnRegisterStaff.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.lightGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        btnRegisterStaff.setContentAreaFilled(false);
        btnRegisterStaff.setOpaque(true);
        btnRegisterStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterStaffActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlRegStaffFormLayout = new javax.swing.GroupLayout(pnlRegStaffForm);
        pnlRegStaffForm.setLayout(pnlRegStaffFormLayout);
        pnlRegStaffFormLayout.setHorizontalGroup(
            pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegStaffFormLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegStaffFormLayout.createSequentialGroup()
                        .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUsernameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLastNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPasswordStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtReEntPasswordStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEmailStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegStaffFormLayout.createSequentialGroup()
                        .addComponent(btnRegisterStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegStaffFormLayout.createSequentialGroup()
                        .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMidNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFirstNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(108, 108, 108))))
            .addGroup(pnlRegStaffFormLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRegStaffFormLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(396, Short.MAX_VALUE)))
        );
        pnlRegStaffFormLayout.setVerticalGroup(
            pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegStaffFormLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMidNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLastNameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsernameStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPasswordStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtReEntPasswordStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmailStaff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRoles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnRegisterStaff)
                .addGap(37, 37, 37))
            .addGroup(pnlRegStaffFormLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlRegStaffFormLayout.createSequentialGroup()
                    .addGap(258, 258, 258)
                    .addComponent(jLabel12)
                    .addContainerGap(165, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout pnlRegStaffLayout = new javax.swing.GroupLayout(pnlRegStaff);
        pnlRegStaff.setLayout(pnlRegStaffLayout);
        pnlRegStaffLayout.setHorizontalGroup(
            pnlRegStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlRegStaffLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(pnlRegStaffForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        pnlRegStaffLayout.setVerticalGroup(
            pnlRegStaffLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRegStaffLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegStaffForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlRegister.add(pnlRegStaff, "card3");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(pnlRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterMemberActionPerformed
        RegisterMember();
    }//GEN-LAST:event_btnRegisterMemberActionPerformed

    private void lblRegMemberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegMemberMouseClicked
        pnlChooseReg.removeAll();
        pnlChooseReg.add(pnlRegMember);
        pnlChooseReg.add(pnlMemberForm);
        pnlChooseReg.repaint();
        pnlChooseReg.revalidate();
    }//GEN-LAST:event_lblRegMemberMouseClicked

    private void lblRegStaffMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblRegStaffMouseClicked
        pnlChooseReg.removeAll();
        pnlChooseReg.add(pnlRegStaff);
        pnlChooseReg.add(pnlRegStaffForm);
        pnlChooseReg.repaint();
        pnlChooseReg.revalidate();
    }//GEN-LAST:event_lblRegStaffMouseClicked

    private void btnRegisterStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterStaffActionPerformed
   
        registerStaff();
        txtFirstNameStaff.setText("");
        txtMidNameStaff.setText("");
        txtLastNameStaff.setText("");
        txtEmailStaff.setText("");
        txtUsernameStaff.setText("");
        txtPasswordStaff.setText("");
        txtReEntPasswordStaff.setText("");
        txtEmailStaff.setText("");
    }//GEN-LAST:event_btnRegisterStaffActionPerformed

    public void registerStaff(){
        try {
            
            String sqlToStaff = "INSERT INTO tbl_staff (fld_first_name, fld_middle_name, fld_last_name, fld_email) " +
                                "VALUES (?, ?, ?, ?)";

            Connection conn = db.createConnection();
            PreparedStatement psStaff = conn.prepareStatement(sqlToStaff, Statement.RETURN_GENERATED_KEYS);

            psStaff.setString(1, txtFirstNameStaff.getText());
            psStaff.setString(2, txtMidNameStaff.getText());
            psStaff.setString(3, txtLastNameStaff.getText());
            psStaff.setString(4, txtEmailStaff.getText());

            int rowsInserted = psStaff.executeUpdate();

            if (rowsInserted > 0) {
                
                ResultSet generatedKeys = psStaff.getGeneratedKeys();
                if (generatedKeys.next()) {
                    int staffId = generatedKeys.getInt(1);

                    
                    String sqlToAccounts = "INSERT INTO tbl_accounts (fld_staff_id, fld_username, fld_password, fld_role) " +
                                           "VALUES (?, ?, ?, ?)";
                    PreparedStatement psAccounts = conn.prepareStatement(sqlToAccounts);

                    String password = passwordCheck();

                    psAccounts.setInt(1, staffId);
                    psAccounts.setString(2, txtUsernameStaff.getText());
                    psAccounts.setString(3, password);
                    psAccounts.setString(4, cmbRoles.getSelectedItem().toString());

                    psAccounts.executeUpdate();
                    psAccounts.close();

                    JOptionPane.showMessageDialog(this, "Account Registered");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Staff Insert Failed");
            }

            psStaff.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.toString());
        }
    }
    
    private void txtReEntPasswordStaffFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtReEntPasswordStaffFocusLost
        
    }//GEN-LAST:event_txtReEntPasswordStaffFocusLost

    public String passwordCheck() {
        String password = new String(txtPasswordStaff.getPassword());
        String rePassword = new String(txtReEntPasswordStaff.getPassword());
        String hashedPass = null;

        if (password.equals(rePassword)) {
            hashedPass = hashPassword(password);
            btnRegisterStaff.setEnabled(true);
        } else {
            btnRegisterStaff.setEnabled(false);
        }

        return hashedPass;
    }

    public static String hashPassword(String password) {
        try {
            // Create SHA-256 digest
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] hashBytes = md.digest(password.getBytes());

            // Convert bytes to hex
            StringBuilder sb = new StringBuilder();
            for (byte b : hashBytes) {
                sb.append(String.format("%02x", b));
            }

            return sb.toString();
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Error hashing password", e);
        }
    }
    
    public void RegisterMember(){
        try {
            String sqlQuery = "INSERT INTO tbl_member(fld_first_name, fld_middle_name, fld_last_name, fld_phone_number, fld_email) " +
                "VALUES (? ,? ,? ,? ,? );";
            
            Connection conn = db.createConnection();
            PreparedStatement psMember = conn.prepareStatement(sqlQuery);
            
            psMember.setString(1, txtFirstNameMember.getText());
            psMember.setString(2, txtMidNameMember.getText());
            psMember.setString(3, txtLastNameMember.getText());
            psMember.setString(4, txtPhoneNumberMember.getText());
            psMember.setString(5, txtEmailMember.getText());
            
            
            txtFirstNameMember.setText("");
            txtMidNameMember.setText("");
            txtLastNameMember.setText("");
            txtPhoneNumberMember.setText("");
            txtEmailMember.setText("");
            
            int rowsInserted = psMember.executeUpdate();
    
            if (rowsInserted > 0) {
                JOptionPane.showMessageDialog(this, "Account Registered");
            } else {
                JOptionPane.showMessageDialog(this, "Account Not Registered");
            }
            
            psMember.close();
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException |
                javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Register().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegisterMember;
    private javax.swing.JButton btnRegisterStaff;
    private javax.swing.JComboBox<String> cmbRoles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRegMember;
    private javax.swing.JLabel lblRegStaff;
    private javax.swing.JPanel pnlChooseReg;
    private javax.swing.JPanel pnlMemberForm;
    private javax.swing.JPanel pnlRegMember;
    private javax.swing.JPanel pnlRegStaff;
    private javax.swing.JPanel pnlRegStaffForm;
    private javax.swing.JPanel pnlRegister;
    private javax.swing.JTextField txtEmailMember;
    private javax.swing.JTextField txtEmailStaff;
    private javax.swing.JTextField txtFirstNameMember;
    private javax.swing.JTextField txtFirstNameStaff;
    private javax.swing.JTextField txtLastNameMember;
    private javax.swing.JTextField txtLastNameStaff;
    private javax.swing.JTextField txtMidNameMember;
    private javax.swing.JTextField txtMidNameStaff;
    private javax.swing.JPasswordField txtPasswordStaff;
    private javax.swing.JTextField txtPhoneNumberMember;
    private javax.swing.JPasswordField txtReEntPasswordStaff;
    private javax.swing.JTextField txtUsernameStaff;
    // End of variables declaration//GEN-END:variables
}
